--DDL Para la definicion de una secuencia
CREATE SEQUENCE "SEQUENCE01"
    MINVALUE 1
    MAXVALUE 999999999999
    INCREMENT BY 1
    START WITH 1;
    
CREATE SEQUENCE "SEQUENCE02"
    MINVALUE 1
    MAXVALUE 999999999999
    INCREMENT BY 1
    START WITH 1;    
    
CREATE SEQUENCE "SEQUENCE03"
    MINVALUE 1
    MAXVALUE 999999999999
    INCREMENT BY 1
    START WITH 1;    
    
CREATE SEQUENCE "SEQUENCE04"
    MINVALUE 1
    MAXVALUE 999999999999
    INCREMENT BY 1
    START WITH 1;    
    
CREATE SEQUENCE "SEQUENCE05"
    MINVALUE 1
    MAXVALUE 999999999999
    INCREMENT BY 1
    START WITH 1;  
    
    
    
----------------------------------------------------------------------------------------------------
--DDL PARA LA DEFINICION DE LA TABLA ESCUELAS
CREATE TABLE ESCUELAS
(
    ID_ESCUELA	NUMBER NOT NULL,
    NOMBRE      VARCHAR2(200),
    DIRECCION   VARCHAR2(500),
    TELEFONO    VARCHAR2(45),
    DIRECTOR_NOMBRE VARCHAR2(200),
    DIRECTOR_APP VARCHAR2(200),
    DIRECTOR_APM VARCHAR2(200),	
    PAGINA_WEB	VARCHAR2(500),
    NUMERO_ESTUDIANTES NUMBER,
    CONSTRAINT ESCUELAS_PK PRIMARY KEY(ID_ESCUELA)
);

--DML para insertar Escuelas
INSERT INTO ESCUELAS (ID_ESCUELA, NOMBRE, DIRECCION, TELEFONO, DIRECTOR_NOMBRE, DIRECTOR_APP, DIRECTOR_APM, PAGINA_WEB, NUMERO_ESTUDIANTES) VALUES (SEQUENCE01.NEXTVAL, 'Preparatoria 1','Cuajimalpa 33','55 2222 3333','Luis','Miguel','Hernandez', 'https://preparatoria1.com.mx', 3);
INSERT INTO ESCUELAS (ID_ESCUELA, NOMBRE, DIRECCION, TELEFONO, DIRECTOR_NOMBRE, DIRECTOR_APP, DIRECTOR_APM, PAGINA_WEB, NUMERO_ESTUDIANTES) VALUES (SEQUENCE01.NEXTVAL, 'Preparatoria 2','Reforma  222','55 2222 3334','Bad','Bunny','Bunny','https://preparatoria1.com.mx', 3);
SELECT * FROM ESCUELAS;


--------------------------------------------------------------------------------------------
--DDL PARA LA DEFINICION DE LA TABLA PROFESORES
CREATE TABLE PROFESORES(
	ID_PROFESOR		NUMBER NOT NULL,
	ESCUELA_ID  	NUMBER NOT NULL,
	NOMBRE      	VARCHAR2(200),
	AP_PATERNO  	VARCHAR2(200),
	AP_MATERNO  	VARCHAR2(200),
	DIRECCION_PROF 	VARCHAR2(500),
	CORREO      	VARCHAR2(200),
	TELEFONO    	VARCHAR2(45),
	SALARIO     	FLOAT,
	FECHA_CONTRATO	DATE,
	CONSTRAINT PROFESORES_PK PRIMARY KEY(ID_PROFESOR),
	--DEFINICION DE LAS LLAVES FORANEAS
	CONSTRAINT PROFESORES_ESCUELAS_FK FOREIGN KEY(ESCUELA_ID) REFERENCES ESCUELAS(ID_ESCUELA)
);

--DML para insertar Profesores
INSERT INTO PROFESORES (ID_PROFESOR,ESCUELA_ID,NOMBRE,AP_PATERNO,AP_MATERNO,DIRECCION_PROF,CORREO,TELEFONO,SALARIO,FECHA_CONTRATO) VALUES (SEQUENCE02.NEXTVAL, 2, 'Mark','Zuckerberg','Elliot','IZTACALCO 444','mark@mail.com','22 1111  9999',30200.57,TO_DATE('2023-10-31', 'YYYY-MM-DD') );
INSERT INTO PROFESORES (ID_PROFESOR,ESCUELA_ID,NOMBRE,AP_PATERNO,AP_MATERNO,DIRECCION_PROF,CORREO,TELEFONO,SALARIO,FECHA_CONTRATO) VALUES (SEQUENCE02.NEXTVAL,1,'Robert','Downey','Jr','TLAHUAC 123','iroman@mail.com','23-3232- 9999',40300.35,TO_DATE('2023-01-01', 'YYYY-MM-DD') );


--------------------------------------------------------------------------------------------
--DDL PARA LA DEFINICION DE LA TABLA ESTUDIANTES
CREATE TABLE ESTUDIANTES(
	ID_ESTUDIANTE   NUMBER NOT NULL,
	ESCUELA_ID      NUMBER NOT NULL,
	NOMBRE	        VARCHAR2(200),
	AP_PATERNO	    VARCHAR2(200),
	AP_MATERNO	    VARCHAR2(200),
	DIRECCION_ALUM	VARCHAR2(200),
	SEMESTRE	    VARCHAR2(100),
	TELEFONO	    VARCHAR2(200),
	CORREO	        VARCHAR2(200),
	FECHA_NACIMIENTO DATE,
	ACTIVO	        NUMBER,
	EGRESO          NUMBER,
	CONSTRAINT ESTUDIANTES_PK PRIMARY KEY(ID_ESTUDIANTE),
	--DEFINICION DE LAS LLAVES FORANEAS
	CONSTRAINT ESTUDIANTES_ESCUELAS_FK FOREIGN KEY(ESCUELA_ID) REFERENCES ESCUELAS (ID_ESCUELA)
);

--DML para insertar Estudiantes
INSERT INTO ESTUDIANTES (ID_ESTUDIANTE,ESCUELA_ID,NOMBRE,AP_PATERNO,AP_MATERNO,DIRECCION_ALUM,SEMESTRE,TELEFONO,CORREO,FECHA_NACIMIENTO,ACTIVO,EGRESO) VALUES (SEQUENCE03.NEXTVAL, 1,'Josue','Soto','Plaza','Azcapotalco 503','PRIMERO','22 1111  9999','josue@mail.com',	TO_DATE('1996-02-16', 'YYYY-MM-DD'),1,0);
INSERT INTO ESTUDIANTES (ID_ESTUDIANTE,ESCUELA_ID,NOMBRE,AP_PATERNO,AP_MATERNO,DIRECCION_ALUM,SEMESTRE,TELEFONO,CORREO,FECHA_NACIMIENTO,ACTIVO,EGRESO) VALUES (SEQUENCE03.NEXTVAL, 1,'Peter','Parker','Guzman',	'Tlalpan 69','SEGUNDO','33-2121-2121','spiderman@mail.com',	TO_DATE('2001-11-01', 'YYYY-MM-DD'),0,0);
INSERT INTO ESTUDIANTES (ID_ESTUDIANTE,ESCUELA_ID,NOMBRE,AP_PATERNO,AP_MATERNO,DIRECCION_ALUM,SEMESTRE,TELEFONO,CORREO,FECHA_NACIMIENTO,ACTIVO,EGRESO) VALUES (SEQUENCE03.NEXTVAL, 2,'Alejandro','Fernandez','Gil',	'Xochimilco 77','PRIMERO','(99)-2121-2121','alex@mail.com',	TO_DATE('1999-06-20', 'YYYY-MM-DD'),0,1);
INSERT INTO ESTUDIANTES (ID_ESTUDIANTE,ESCUELA_ID,NOMBRE,AP_PATERNO,AP_MATERNO,DIRECCION_ALUM,SEMESTRE,TELEFONO,CORREO,FECHA_NACIMIENTO,ACTIVO,EGRESO) VALUES (SEQUENCE03.NEXTVAL, 2,'Cynthia','Alcantara','Ramos','Coyoacan 79','SEGUNDO','23 3232 9999','cynthia@gmail.com',	TO_DATE('1990-05-11', 'YYYY-MM-DD'),1,0);


--------------------------------------------------------------------------------------------
--DDL PARA LA DEFINICION DE LA TABLA CLASES
CREATE TABLE CLASES(
	ID_CLASE    NUMBER NOT NULL,
	PROFESOR_ID NUMBER NOT NULL,
	MATERIA	    VARCHAR2(200),
	SALON       VARCHAR2(45),
	HR_INICIO   VARCHAR2(20),
	HR_FIN      VARCHAR2(20),
	LUNES       NUMBER,
	MARTES      NUMBER,
	MIERCOLES   NUMBER,
	JUEVES      NUMBER,
	VIERNES     NUMBER,
	SABADO      NUMBER,
	DOMINGO     NUMBER,
	CONSTRAINT CLASES_PK PRIMARY KEY(ID_CLASE),
	--DEFINICION DE LAS LLAVES FORANEAS
	CONSTRAINT CLASES_PROFESORES_FK FOREIGN KEY(PROFESOR_ID) REFERENCES PROFESORES (ID_PROFESOR)
);

--DML para insertar Clases
INSERT INTO CLASES (ID_CLASE,PROFESOR_ID,MATERIA,SALON,HR_INICIO,HR_FIN,LUNES,MARTES,MIERCOLES,JUEVES,VIERNES,SABADO,DOMINGO) VALUES (SEQUENCE04.NEXTVAL,1,'ESPANOL','A11','11:00','13:00',1,0,1,0,1,0,0);
INSERT INTO CLASES (ID_CLASE,PROFESOR_ID,MATERIA,SALON,HR_INICIO,HR_FIN,LUNES,MARTES,MIERCOLES,JUEVES,VIERNES,SABADO,DOMINGO) VALUES (SEQUENCE04.NEXTVAL,1,'CIENCIAS','B22','11:00','13:00',0,1,0,1,0,1,0);
INSERT INTO CLASES (ID_CLASE,PROFESOR_ID,MATERIA,SALON,HR_INICIO,HR_FIN,LUNES,MARTES,MIERCOLES,JUEVES,VIERNES,SABADO,DOMINGO) VALUES (SEQUENCE04.NEXTVAL,2,'PROGRAMACION','C02','11:00','13:00',0,1,0,1,1,0,0);
INSERT INTO CLASES (ID_CLASE,PROFESOR_ID,MATERIA,SALON,HR_INICIO,HR_FIN,LUNES,MARTES,MIERCOLES,JUEVES,VIERNES,SABADO,DOMINGO) VALUES (SEQUENCE04.NEXTVAL,2,'PROGRAMACION','C02','13:00','15:00',0,1,0,1,1,0,0);
INSERT INTO CLASES (ID_CLASE,PROFESOR_ID,MATERIA,SALON,HR_INICIO,HR_FIN,LUNES,MARTES,MIERCOLES,JUEVES,VIERNES,SABADO,DOMINGO) VALUES (SEQUENCE04.NEXTVAL,2,'PROGRAMACION_AVANZADA','C02','09:00','16:00',0,0,0,0,0,0,1);


--------------------------------------------------------------------------------------------
--DDL PARA LA DEFINICION DE LA TABLA CALIFICACIONES
CREATE TABLE CALIFICACIONES(
	ID_CALIFICACION NUMBER NOT NULL,
	ESTUDIANTE_ID   NUMBER NOT NULL,
	CLASE_ID        NUMBER NOT NULL,
	CALIFICACION    FLOAT,
	NOTA            VARCHAR2(500),
	CONSTRAINT CALIFICACIONES_PK PRIMARY KEY(ID_CALIFICACION),
	--DEFINICION DE LAS LLAVES FORANEAS
	CONSTRAINT CALIFICACIONES_ESTUDIANTES_FK FOREIGN KEY(ESTUDIANTE_ID) REFERENCES ESTUDIANTES (ID_ESTUDIANTE),
	CONSTRAINT CLASES_ESTUDIANTES_FK FOREIGN KEY(CLASE_ID) REFERENCES CLASES (ID_CLASE)
);

--DML para insertar Calificaciones
INSERT INTO CALIFICACIONES ( ID_CALIFICACION, ESTUDIANTE_ID, CLASE_ID, CALIFICACION,NOTA) VALUES (SEQUENCE05.NEXTVAL, 1,	2,	8,	NULL);
INSERT INTO CALIFICACIONES ( ID_CALIFICACION, ESTUDIANTE_ID, CLASE_ID, CALIFICACION,NOTA) VALUES (SEQUENCE05.NEXTVAL, 2,	5,	NULL,NULL);	
INSERT INTO CALIFICACIONES ( ID_CALIFICACION, ESTUDIANTE_ID, CLASE_ID, CALIFICACION,NOTA) VALUES (SEQUENCE05.NEXTVAL, 1,    1,	5,	'se pelio con un companero Y REPROBO');
INSERT INTO CALIFICACIONES ( ID_CALIFICACION, ESTUDIANTE_ID, CLASE_ID, CALIFICACION,NOTA) VALUES (SEQUENCE05.NEXTVAL, 3,	5,	10,	'excelente alumno');
INSERT INTO CALIFICACIONES ( ID_CALIFICACION, ESTUDIANTE_ID, CLASE_ID, CALIFICACION,NOTA) VALUES (SEQUENCE05.NEXTVAL, 4,	3,	10,	NULL);
INSERT INTO CALIFICACIONES ( ID_CALIFICACION, ESTUDIANTE_ID, CLASE_ID, CALIFICACION,NOTA) VALUES (SEQUENCE05.NEXTVAL, 4,	4,	9,  NULL);







--Mostrar trablas
SELECT * FROM ESCUELAS;
SELECT * FROM PROFESORES;
SELECT * FROM ESTUDIANTES;
SELECT * FROM CLASES;
SELECT * FROM CALIFICACIONES;

commit;


